# Generated by Django 4.1.5 on 2023-01-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Stud_Name',
            field=models.CharField(max_length=69),
        ),
        migrations.AlterField(
            model_name='student',
            name='Stud_Password',
            field=models.CharField(max_length=34),
        ),
    ]
