# Generated by Django 4.1.5 on 2023-01-09 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=45)),
                ('Age', models.IntegerField()),
                ('Phno', models.BigIntegerField()),
                ('City_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.city')),
                ('Course_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.course')),
            ],
        ),
    ]
